config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create] do
    collection do
      post 'downgrade'
    end
  end

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

  devise_for :users
  resources :users, only: [:edit, :update]

  get 'about' => 'welcome#about'
  get 'index' => 'welcome#index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wiki

  def new
    #@wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new
    authorize @collaborator
    #@users = @wiki.wiki_collaborators  # these are users for this wiki only (not all users)
    @users = User.all
    #raise
  end

  def create
    #@wiki = Wiki.find(params[:wiki_id])
    @user = User.find(params[:user])
    @collaborator = Collaborator.new(wiki: @wiki, user: @user)
    authorize @collaborator
    if @collaborator.save
      flash[:notice] = "You are now a collaborator for #{@wiki.title}."
      redirect_to :back
      #raise
    end
  end

  def destroy
      #@wiki = Wiki.find(params[:wiki_id])
      #@user = User.find(params[:id])
      #@collaborator = @wiki.collaborators.find_by(user_id: @user.id)
      @collaborator = @wiki.collaborators.find_by(user_id: params[:id])
      authorize @collaborator
      #raise
      if @collaborator.destroy
        flash[:notice] = "You are not a collaborator for this wiki anymore."
        redirect_to :back
      end
  end

  private
  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end

end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/views/collaborators/new.html.erb
<h1>Manage Collaborators for: </h1>

<!-- <h4><%#= markdown_to_html(@wiki.title) %></h4> -->
<h4><%= @wiki.title %></h4>

<table class="table table-hover">
  <thead>
    <tr>
      <th><h4>Users</h4></th>
        <th>email</th>
        <th>role</th>
        <th>access</th>
    </tr>
  </thead>

  <% @users.each do |user| %>
  <tbody>

    <tr>
      <% if user != current_user %>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>

        <% if @wiki.wiki_collaborators.include?(user) %>
          <td><%= button_to "Remove Collaborator", wiki_collaborator_path(@wiki, user), method: :delete, class: "btn btn-sm btn-danger" %></td>
        <% else %>
          <td><%= button_to "Add Collaborator", wiki_collaborators_path(@wiki, user: user), class: "btn btn-sm btn-success" %></td>
        <% end %>

      <% end %>
    </tr>

  </tbody>

  <% end %>
  <%= link_to "Back to edit", edit_wiki_path(@wiki), class: "btn btn-md btn-primary" %>
</table>