config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create] do
    collection do
      post 'downgrade'
    end
  end

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

  devise_for :users
  resources :users, only: [:edit, :update]

  get 'about' => 'welcome#about'
  get 'index' => 'welcome#index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div class="about">
  <h1>About WikiLand</h1>

  <h3>User Roles:</h3>
  <ul>
    <h4>
      <li>Guest(un-signed)</li>
      <ul>
          <li>View all public wikis</li>
      </ul>
      <li>Standard User</li>
      <ul>
        <li>Free</li>
        <li>Create and edit public wikis</li>
        <li>Can participate as a collaborator on a private wiki</li>
        <li>Delete you own public wikis</li>
      </ul>
      <li>Premium User</li>
      <ul>
        <li>One time fee of $15.00</li>
        <li>Create and edit public wikis</li>
        <li>Create and edit private wikis</li>
        <li>Add and/or remove collaborators to private wikis</li>
        <li>Delete you own private wikis</li>
      </ul>
      <li>Admin User</li>
      <ul>
        <li>Assigned only</li>
        <li>Access to everything</li>
      </ul>
    </h4>
  </ul>


  <h3>Wiki type</h3>
  <ul>
    <h4>
      <li>Public Wikis</li>
      <ul>
          <li>Can be viewed by everyone</li>
      </ul>
      <li>Private Wikis</li>
      <ul>
        <li>Accessible by admin, premium or collaborator users only</li>
      </ul>
    </h4>
  </ul>
</div>

app/views/welcome/about.html.haml
.about
  %h1 About Wiki

  %h3
    User Roles:
    %ul
      %h4
        %li
          Guest(un-signed)
          %ul
            %li
              View all public wikis
            %li
              Standard User
            %ul
              %li Free
              %li Create and edit public wikis
              %li Can participate as a collaborator on a private wiki
              %li Delete you own public wikis
            %liPremium User
          %ul
            %li
              One time fee of $15.00
            %li
              Create and edit public wikis
            %li
              Create and edit private wikis
            %li
              Add and/or remove collaborators to private wikis
            %li
              Delete you own private wikis
            %li Admin User
          %ul
            %li
              Assigned only
            %li
              Access to everything

  %h3
    Wiki type
  %ul
    %h4
      %li
        Public Wikis
      %ul
        %li
          Can be viewed by everyone
        %li
          Private Wikis
      %ul
        %li Accessible by admin, premium or collaborator users only

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 style="font-family: 'Cormorant SC', serif; font-size: 100px;">WikiLand</h1><hr> 
  <p>
    Wikis are a great way to collaborate on community-sourced content. Whether the wiki is for a hobby or work-related project, you will build an app that lets users create their own wikis and share them publicly or privately with other collaborators.
  </p>
  <p><a class="btn btn-primary btn-md" href="/about" role="button">Learn more</a>
  <%= link_to "Sign up", new_user_registration_path	, class: "btn btn-md btn-primary" if !current_user %><br/></p>
</div>

<% if current_user && current_user.standard? %>

    <div class="well bottom-well rows col-md-5">
      <%= link_to "Upgrade to premium", new_charge_path, class: "btn btn-md btn-primary" %><br/><hr>
      <ul>
        <li>Create private or public wikis</li>
        <li>Access your private wikis</li>
        <li>Access to all public wikis</li>
      </ul>
    </div>

<% elsif current_user && current_user.premium? %>

  <div class="well bottom-well rows col-md-5">
    <%= link_to "Downgrade back to standard", downgrade_charges_path, method: :post, class: "btn btn-md btn-primary", data: {confirm: 'Are you sure?'} %><br/><hr>
    <ul>
      <li>If you have private wikis they will be converted to public wikis</li>
      <li>Create public wikis</li>
      <li>Access to all public wikis</li>
    </ul>
  </div>

<% end %>

app/views/welcome/index.html.haml
.jumbotron
  %h1 Blocipedia3
  %hr
  %p
    Wikis are a great way to collaborate on community-sourced content. Whether the wiki is for a hobby or work-related project, you will build an app that lets users create their own wikis and share them publicly or privately with other collaborators.

  %p
    %a.btn.btn-primary.btn-md{href: "/about", role: "button"} Learn more
    = link_to "Sign up", new_user_registration_path	, class: "btn btn-md btn-primary" if !current_user
    %br



- if current_user && current_user.standard?

  .well.bottom-well.rows.col-md-5
    = link_to "Upgrade to premium", new_charge_path, class: "btn btn-md btn-primary"
    %br
    %hr
      %ul
        %li Create private or public wikis
        %liAccess your private wikis
        %liAccess to all public wikis

- elsif current_user && current_user.premium?

  .well.bottom-well.rows.col-md-5
    = link_to "Downgrade back to standard", downgrade_charges_path, method: :post, class: "btn btn-md btn-primary", data: {confirm: 'Are you sure?'}
    %br
    %hr
    %ul
      %li If you have private wikis they will be converted to public wikis
      %li Create public wikis
      %li Access to all public wikis

app/views/welcome/ori_about.html.erb
<div class="about">
  <h1>About Wiki</h1>

  <h3>User Roles:</h3>
  <ul>
    <h4>
      <li>Guest(un-signed)</li>
      <ul>
          <li>View all public wikis</li>
      </ul>
      <li>Standard User</li>
      <ul>
        <li>Free</li>
        <li>Create and edit public wikis</li>
        <li>Can participate as a collaborator on a private wiki</li>
        <li>Delete you own public wikis</li>
      </ul>
      <li>Premium User</li>
      <ul>
        <li>One time fee of $15.00</li>
        <li>Create and edit public wikis</li>
        <li>Create and edit private wikis</li>
        <li>Add and/or remove collaborators to private wikis</li>
        <li>Delete you own private wikis</li>
      </ul>
      <li>Admin User</li>
      <ul>
        <li>Assigned only</li>
        <li>Access to everything</li>
      </ul>
    </h4>
  </ul>


  <h3>Wiki type</h3>
  <ul>
    <h4>
      <li>Public Wikis</li>
      <ul>
          <li>Can be viewed by everyone</li>
      </ul>
      <li>Private Wikis</li>
      <ul>
        <li>Accessible by admin, premium or collaborator users only</li>
      </ul>
    </h4>
  </ul>
</div>

app/views/welcome/ori_index.html.erb
<div class="jumbotron">
  <h1>Blocipedia3</h1><hr>
  <p>
    Wikis are a great way to collaborate on community-sourced content. Whether the wiki is for a hobby or work-related project, you will build an app that lets users create their own wikis and share them publicly or privately with other collaborators.
  </p>
  <p><a class="btn btn-primary btn-md" href="/about" role="button">Learn more</a>
  <%= link_to "Sign up", new_user_registration_path	, class: "btn btn-md btn-primary" if !current_user %><br/></p>
</div>

<% if current_user && current_user.standard? %>

    <div class="well bottom-well rows col-md-5">
      <%= link_to "Upgrade to premium", new_charge_path, class: "btn btn-md btn-primary" %><br/><hr>
      <ul>
        <li>Create private or public wikis</li>
        <li>Access your private wikis</li>
        <li>Access to all public wikis</li>
      </ul>
    </div>

<% elsif current_user && current_user.premium? %>

  <div class="well bottom-well rows col-md-5">
    <%= link_to "Downgrade back to standard", downgrade_charges_path, method: :post, class: "btn btn-md btn-primary", data: {confirm: 'Are you sure?'} %><br/><hr>
    <ul>
      <li>If you have private wikis they will be converted to public wikis</li>
      <li>Create public wikis</li>
      <li>Access to all public wikis</li>
    </ul>
  </div>

<% end %>