config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create] do
    collection do
      post 'downgrade'
    end
  end

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

  devise_for :users
  resources :users, only: [:edit, :update]

  get 'about' => 'welcome#about'
  get 'index' => 'welcome#index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user#, optional: true
  has_many :collaborators, dependent: :destroy
  has_many :wiki_collaborators, through: :collaborators, source: :user

  validates :title, :body, :slug, presence: true

  scope :public_wikis, -> { Wiki.where(private: false) }
  scope :private_wikis, -> (user1){ Wiki.where(private: true).where(user: user1)  } #
  scope :private_wikis_admin, -> { where(private: true) }

  extend FriendlyId
  friendly_id :title, use: :slugged   # :title is the attribute for the slug

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  require 'will_paginate/array'
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]

  def index
    #@wikis = Wiki.all
    #authorize @wikis

    @wikis = policy_scope(Wiki).paginate(page: params[:page], per_page: 10)
    @public_wikis = Wiki.public_wikis.paginate(page: params[:page], per_page: 10)
    #
    if current_user && current_user.admin?
      @private_wikis = Wiki.private_wikis_admin.paginate(page: params[:page], per_page: 10)
    else
      @private_wikis = ((Wiki.private_wikis(current_user) + current_user.wiki_collaborations)).paginate(page: params[:page], per_page: 10) if current_user#.paginate(page: params[:page], per_page: 10) #if current_user
    end
  end

  def show
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki
    #byebug
    if @wiki.save
      flash[:success] = "Your wiki was saved successfully!"
      redirect_to(@wiki)
    else
      flash[:error] = "Your wiki was not saved. Please try again."
      render :new
    end
  end

  def edit
    authorize @wiki
  end

  def update
    authorize @wiki
    if @wiki.update_attributes(wiki_params)
      flash[:success] = "Your wiki was updated successfully!"
      redirect_to(@wiki)
    else
      flash[:error] = "Your wiki was not updated. Please try again."
      render :edit
    end
  end

  def destroy
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "Your wiki was deleted."
      redirect_to wikis_url
    end
  end

  private
  def set_wiki
    #@wiki = Wiki.find(params[:id])
    @wiki = Wiki.friendly.find(params[:id])
  end

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>

<div class="rows">
  <div class="col-md-7">

    <div form-group>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control",  placeholder: "Enter title" %><br/>
    </div>
    <div form-group>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: "form-control",  placeholder: "Enter body" %><br/>
    </div>

    <%# if (current_user.premium? || current_user.admin?) %>
    <% if  @wiki.id  && ( @wiki.user == current_user  &&  current_user.premium?) || current_user.admin? %>
    <div form-group>
      <%= f.check_box :private %>
      <%= f.label :private,  "Private wiki"%>
    </div>
      <%#= f.label :private, class: "Private" do %>
      <%#= f.check_box :private %> <!--Private wiki-->
      <%# end %>

      <% elsif (!@wiki.id && current_user.premium?) || current_user.admin? %>
      <div form-group>
        <%= f.check_box :private %>
        <%= f.label :private,  "Private wiki"%>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit class: "btn btn-md btn-success" %>
      <%= link_to "Cancel", @wiki, class: "btn btn-md btn-primary" %>
    </div>

  </div>
</div>

<% end %>

<div class="col-md-12">
  <% if @wiki.private && (@wiki.user == current_user || current_user.admin?) %>
    <hr>
    <h4>Manage private collaborators</h4>
    <%= link_to "Add or remove private collaborators", new_wiki_collaborator_path(@wiki), class: "btn btn-md btn-primary" %>
  <% end %>
</div>

app/views/wikis/_form.html.haml
= form_for(@wiki) do |f|

  .rows
    .col-md-7

      .form-group
        = f.label :title
        = f.text_field :title, class: "form-control",  placeholder: "Enter title"
        %br

      .form-group
        = f.label :body
        = f.text_area :body, rows: 8, class: "form-control",  placeholder: "Enter body"
        %br

      -if  @wiki.id  && ( @wiki.user == current_user  &&  current_user.premium?) || current_user.admin?
        .form-group
          = f.check_box :private
          = f.label :private,  "Private wiki"

      - elsif (!@wiki.id && current_user.premium?) || current_user.admin?
        .form-group
          = f.check_box :private
          = f.label :private,  "Private wiki"

      .actions
        = f.submit class: "btn btn-md btn-success"
        = link_to "Cancel", @wiki, class: "btn btn-md btn-primary"

    .col-md-12
      -if @wiki.private && (@wiki.user == current_user || current_user.admin?)
        %hr
          %h4 Manage private collaborators
          = link_to "Add or remove private collaborators", new_wiki_collaborator_path(@wiki), class: "btn btn-md btn-primary"

app/views/wikis/_wiki.html.erb
<tr>
  <td>

      <%#= link_to (markdown_to_html wiki.title), wiki_path(wiki) %>
      <h4><%= link_to wiki.title, wiki %></h4>
      <h5><%= truncate wiki.body, length: 75, separator: ' ' %></h5>

  </td>
  <td><%= link_to "Edit", edit_wiki_path(wiki), class: "btn btn-md btn-success" if policy(wiki).edit? %></td>
  <td><%= link_to "Delete", wiki_path(wiki), method: :delete, class: "btn btn-md btn-danger", data: {confirm: "Are you sure?"} if policy(wiki).destroy? %></td>
</tr>

<%# @wikis.each do |wiki| %>
  <%#= wiki.title %>
  <%#= link_to (wiki.title), wiki %>

<%# end %>

app/views/wikis/_wiki.html.haml
%tr
  %td>
    %h4
      = link_to wiki.title, wiki
      %h5
        = truncate wiki.body, length: 75, separator: ' '

  %td
    = link_to "Edit", edit_wiki_path(wiki), class: "btn btn-md btn-success" if policy(wiki).edit?
  %td
    = link_to "Delete", wiki_path(wiki), method: :delete, class: "btn btn-md btn-danger", data: {confirm: "Are you sure?"} if policy(wiki).destroy?

app/views/wikis/edit.html.haml
%h1
  Edit:
  = @wiki.title
= render 'form'

app/views/wikis/new.html.erb
<h1>New wiki</h1>
<%= render 'form' %>

app/views/wikis/ori_edit.html.erb
<h1>Edit: <%= @wiki.title %></h1>
<%= render 'form' %>

app/views/wikis/ori_form.html.erb
<%= form_for(@wiki) do |f| %>

<div class="rows">
  <div class="col-md-7">

    <div form-group>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control",  placeholder: "Enter title" %><br/>
    </div>
    <div form-group>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: "form-control",  placeholder: "Enter body" %><br/>
    </div>

    <%# if (current_user.premium? || current_user.admin?) %>
    <% if  @wiki.id  && ( @wiki.user == current_user  &&  current_user.premium?) || current_user.admin? %>
    <div form-group>
      <%= f.check_box :private %>
      <%= f.label :private,  "Private wiki"%>
    </div>
      <%#= f.label :private, class: "Private" do %>
      <%#= f.check_box :private %> <!--Private wiki-->
      <%# end %>

      <% elsif (!@wiki.id && current_user.premium?) || current_user.admin? %>
      <div form-group>
        <%= f.check_box :private %>
        <%= f.label :private,  "Private wiki"%>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit class: "btn btn-md btn-success" %>
      <%= link_to "Cancel", @wiki, class: "btn btn-md btn-primary" %>
    </div>

  </div>
</div>

<% end %>

<div class="col-md-12">
  <% if @wiki.private && (@wiki.user == current_user || current_user.admin?) %>
    <hr>
    <h4>Manage private collaborators</h4>
    <%= link_to "Add or remove private collaborators", new_wiki_collaborator_path(@wiki), class: "btn btn-md btn-primary" %>
  <% end %>
</div>

app/views/wikis/ori_index.html.erb
<!-- <h1>Wikis</h1> -->

<div class="container">

  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#all-wikis">All Wikis</a></li>

    <% if (current_user && current_user.premium?) || ( current_user && current_user.wiki_collaborations.present? ) || (current_user && current_user.admin?) %>
      <li><a data-toggle="tab" href="#public-wikis">Public Wikis</a></li>
      <li><a data-toggle="tab" href="#private-wikis">Private Wikis</a></li>
    <% end %>

  </ul>

  <div class="tab-content">
    <div id="all-wikis" class="tab-pane fade in active">
      <h3>All Wikis(<%= all_wikis_count %>)</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <th><h4>Title</h4></th>

            <% if current_user %>
              <th>Edit</th>
              <th>Delete</th>
            <% end %>

          </tr>
        </thead>
        <tbody>
          <%#= render @wikis %>
          <%= render partial: 'wiki', locals: { wikis: @wikis }, collection: @wikis %>

        </tbody>
      </table>
      <%#= link_to "Create new wiki", new_wiki_path, class: "btn btn-md btn-success" if policy(@wikis).create? %>
      <!-- <span id="create-new-wiki"><%= link_to "Create new wiki", new_wiki_path, class: "btn btn-md btn-success" if policy(Wiki).new? %></span> -->
      <%= link_to "Create new wiki", new_wiki_path, id: "create-new-wiki", class: "btn btn-md btn-success" if policy(Wiki).create? %><br/>
      <%#= will_paginate @wikis %>
      <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
    </div>

    <% if current_user %>

    <div id="public-wikis" class="tab-pane fade">
      <h3>Public Wikis(<%= public_wikis_count %>)</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <th><h4>Title</h4></th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          <%#= render @wikis %>
          <%= render partial: 'wiki', locals: { wikis: @public_wikis }, collection: @public_wikis %>
          <%#= render partial: 'wiki', locals: { wikis: @wikis}, collection: @wikis%>
        </tbody>
      </table>
      <%#= link_to "Create new wiki", new_wiki_path, class: "btn btn-md btn-success" if policy(@wikis).create? %>
      <%= link_to "Create new wiki", new_wiki_path, class: "btn btn-md btn-success" if policy(Wiki).new? %><br/> <!-- OK -->
      <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
    </div>

    <div id="private-wikis" class="tab-pane fade">

      <h3>Private Wikis(<%= private_wikis_count %>)</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <th><h4>Title</h4></th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          <%#= render @wikis %>
          <%= render partial: 'wiki', locals: { wikis: @private_wikis }, collection: @private_wikis %>
        </tbody>
      </table>
      <%= link_to "Create new wiki", new_wiki_path, class: "btn btn-md btn-success" if policy(Wiki).new? %><br/>
      <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>

    </div>

    <% end %>

  </div>
</div>


<!-- original  -->
<!--
<table class="table table-hover">
    <thead>
      <tr>
        <th><h4>Tile</h4></th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <%#= render @wikis %>
      <%#= render partial: 'wiki', locals: { wikis: @wikis }, collection: @wikis %>
    </tbody>
  </table>
  <%#= link_to "Create new wiki", new_wiki_path, class: "btn btn-md btn-success" if policy(@wikis).create? %>
  <%#= link_to "Create new wiki", new_wiki_path, class: "btn btn-md btn-success" if policy(Wiki).new? %>
</div>

<br/><br/><br/>
-->

app/views/wikis/ori_new.html.erb
<h1>New wiki</h1>
<%= render 'form' %>

app/views/wikis/ori_show.html.erb
<% if @wiki.private? %>
  <h2>Private Wiki</h2>
<% else %>
  <h2>Public Wiki</h2>
<% end %>

<h2><%= @wiki.title %></h2>
<h5><%#= Markdown.new(@wiki.body).to_html.html_safe %></h5>
<h5><%= markdown_to_html(@wiki.body) %></h5>

<hr>

<%= link_to "Edit", edit_wiki_path(@wiki), class: "btn btn-md btn-success" if policy(@wiki).edit? %>
<%= link_to "Delete", wiki_path(@wiki), method: :delete, class: "btn btn-md btn-danger", data: {confirm: "Are you sure?"} if policy(@wiki).destroy? %>
<%= link_to "All Wikis", wikis_path, class: "btn btn-md btn-primary" %>

<% if @wiki.private? %>
  <hr>

  <h3>Collaborators for this wiki:</h3>

  <% if @wiki.wiki_collaborators.present? %>

    <% @wiki.wiki_collaborators.each do |collaborator| %>
      <h4><%= collaborator.name %></h4>
    <% end %>

  <% else %>
    <h5>None</h5>
  <% end %>

<% end %>

app/views/wikis/ori_wiki.html.erb
<tr>
  <td>

      <%#= link_to (markdown_to_html wiki.title), wiki_path(wiki) %>
      <h4><%= link_to wiki.title, wiki %></h4>
      <h5><%= truncate wiki.body, length: 75, separator: ' ' %></h5>

  </td>
  <td><%= link_to "Edit", edit_wiki_path(wiki), class: "btn btn-md btn-success" if policy(wiki).edit? %></td>
  <td><%= link_to "Delete", wiki_path(wiki), method: :delete, class: "btn btn-md btn-danger", data: {confirm: "Are you sure?"} if policy(wiki).destroy? %></td>
</tr>

<%# @wikis.each do |wiki| %>
  <%#= wiki.title %>
  <%#= link_to (wiki.title), wiki %>

<%# end %>

app/views/wikis/show.html.erb
<% if @wiki.private? %>
  <h2>Private Wiki</h2>
<% else %>
  <h2>Public Wiki</h2>
<% end %>

<h2><%= @wiki.title %></h2>
<h5><%#= Markdown.new(@wiki.body).to_html.html_safe %></h5>
<h5><%= markdown_to_html(@wiki.body) %></h5>

<hr>

<%= link_to "Edit", edit_wiki_path(@wiki), class: "btn btn-md btn-success" if policy(@wiki).edit? %>
<%= link_to "Delete", wiki_path(@wiki), method: :delete, class: "btn btn-md btn-danger", data: {confirm: "Are you sure?"} if policy(@wiki).destroy? %>
<%= link_to "All Wikis", wikis_path, class: "btn btn-md btn-primary" %>

<% if @wiki.private? %>
  <hr>

  <h3>Collaborators for this wiki:</h3>

  <% if @wiki.wiki_collaborators.present? %>

    <% @wiki.wiki_collaborators.each do |collaborator| %>
      <h4><%= collaborator.name %></h4>
    <% end %>

  <% else %>
    <h5>None</h5>
  <% end %>

<% end %>

app/views/wikis/show.html.haml
- if @wiki.private?
  %h2 Private Wiki
- else
  %h2 Public Wiki

%h2
  = @wiki.title
%h5
  = markdown_to_html(@wiki.body)
  %hr

  = link_to "Edit", edit_wiki_path(@wiki), class: "btn btn-md btn-success" if policy(@wiki).edit?
  = link_to "Delete", wiki_path(@wiki), method: :delete, class: "btn btn-md btn-danger", data: {confirm: "Are you sure?"} if policy(@wiki).destroy?
  = link_to "All Wikis", wikis_path, class: "btn btn-md btn-primary"

- if @wiki.private?
  %hr

  %h3 Collaborators for this wiki:

  - if @wiki.wiki_collaborators.present?

    - @wiki.wiki_collaborators.each do |collaborator|
      %h4 = collaborator.name

  - else
    %h5 None