config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create] do
    collection do
      post 'downgrade'
    end
  end

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

  devise_for :users
  resources :users, only: [:edit, :update]

  get 'about' => 'welcome#about'
  get 'index' => 'welcome#index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <span>Joe Garcia 2017 &copy </span>
  </div>
</footer>

app/views/layouts/_footer.html.haml
%footer
 .navbar-default.navbar-fixed-bottom
  .container-fluid
  %span Joe Garcia 2017 &copy

app/views/layouts/_navbar.html.erb
<!-- <nav class="navbar navbar-inverse"> -->
<nav class="navbar navbar" style="background:lightgray">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="/index">Blocipedia</a> -->
      <div class="<%= active?(index_path) %> navbar-brand">
        <%= link_to "WikiLand", index_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="index">Home</a></li> -->
        <!-- <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li> -->
        <!-- <li><a href="#">Page 2</a></li>
        <li><a href="#">Page 3</a></li> -->
        <li class="<%= active?(wikis_path)%>"><%= link_to 'Home', wikis_path %></li>
        <li class="<%= active?(about_path)%>"><%= link_to 'About', about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li> -->
        <% if current_user %>
          <li><%= link_to "Premium", "#" if current_user.premium? %></li>
          <li><%= link_to (current_user.name || current_user.email), edit_user_registration_path(current_user) %></li>
          <!-- <li><%= link_to (current_user.name || current_user.email), "#", class: "glyphicons glyphicons-user" %></li> -->
          <li><%= link_to ' Logout', destroy_user_session_path, class: "glyphicon glyphicon-log-out", method: :delete, data: {confirm: 'Are you sure?'} %></li>
        <% else %>
          <li><%= link_to ' Sign Up', new_user_registration_path, class: "glyphicon glyphicon-user" %></li>
          <li><%= link_to ' Login', new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar{:style => "background:lightgray"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#myNavbar", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %div{:class => "#{active?(index_path)} navbar-brand"}
        = link_to "Blocipedia", index_path
    #myNavbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{:class => "#{active?(wikis_path)}"}= link_to 'Home', wikis_path
        %li{:class => "#{active?(about_path)}"}= link_to 'About', about_path
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li= link_to "Premium", "#" if current_user.premium?
          %li= link_to (current_user.name || current_user.email), edit_user_registration_path(current_user)
          %li= link_to ' Logout', destroy_user_session_path, class: "glyphicon glyphicon-log-out", method: :delete, data: {confirm: 'Are you sure?'}
        - else
          %li= link_to ' Sign Up', new_user_registration_path, class: "glyphicon glyphicon-user"
          %li= link_to ' Login', new_user_session_path, class: "glyphicon glyphicon-log-in"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikiLand</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Cormorant+SC" rel="stylesheet">
  </head>

  <body class="background-body">

    <%= render 'layouts/navbar' %>

      <div class="container">

        <%= render 'layouts/shared/flash_message' %>

        <%= yield %>

        <%= render 'layouts/footer' %>

    </div>

  </body>

</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blocipedia3
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body.background-body

    = render 'layouts/navbar'

    .container

      = render 'layouts/shared/flash_message'

      = yield

      = render 'layouts/footer'

app/views/layouts/ori_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="background-body">

    <%= render 'layouts/navbar' %>

      <div class="container">

        <%= render 'layouts/shared/flash_message' %>

        <%= yield %>

        <%= render 'layouts/footer' %>

    </div>

  </body>

</html>

app/views/layouts/ori_footer.html.erb
<footer class="navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <span>Joe Garcia 2017 &copy </span>
  </div>
</footer>

app/views/layouts/ori_navbar.html.erb
<!-- <nav class="navbar navbar-inverse"> -->
<nav class="navbar navbar" style="background:lightgray">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="/index">Blocipedia</a> -->
      <div class="<%= active?(index_path) %> navbar-brand">
        <%= link_to "Blocipedia", index_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="index">Home</a></li> -->
        <!-- <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li> -->
        <!-- <li><a href="#">Page 2</a></li>
        <li><a href="#">Page 3</a></li> -->
        <li class="<%= active?(wikis_path)%>"><%= link_to 'Home', wikis_path %></li>
        <li class="<%= active?(about_path)%>"><%= link_to 'About', about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li> -->
        <% if current_user %>
          <li><%= link_to "Premium", "#" if current_user.premium? %></li>
          <li><%= link_to (current_user.name || current_user.email), edit_user_registration_path(current_user) %></li>
          <!-- <li><%= link_to (current_user.name || current_user.email), "#", class: "glyphicons glyphicons-user" %></li> -->
          <li><%= link_to ' Logout', destroy_user_session_path, class: "glyphicon glyphicon-log-out", method: :delete, data: {confirm: 'Are you sure?'} %></li>
        <% else %>
          <li><%= link_to ' Sign Up', new_user_registration_path, class: "glyphicon glyphicon-user" %></li>
          <li><%= link_to ' Login', new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>